//a list of all the quotes for the ancestor
const kAncestorQuoteList = [
  'In time, you will know the tragic extent of my failings...',
  'You remember our venerable house, opulent and imperial...',
  'Steel yourself and remember: there can be no bravery without madness.',
  'The old road will take you to hell, but in that gaping abyss we will find our redemption.',
  'Dispatch this thug in brutal fashion, that all may hear of your arrival!',
  'Leave nothing unchecked, there is much to be found in forgotten places.',
  'Send these vermin a message: the rightful owner has returned, and their kind is no longer welcome.',
  'This squalid hamlet, these corrupted lands, they are yours now, and you are bound to them.',
  'The cost of preparedness - measured now in gold, later in blood.',
  'Women and men; soldiers and outlaws; fools and corpses. '
      'All will find their way to us now that the road is clear.',
  '	Fresh kegs, cards, and curtained rooms promise solace to the weary and the broken alike.',
  'The bellows blast once again! The forge stands ready to make weapons of war.',
  'Curiosity, interest, and obsession — mile markers on my road to damnation.',
  'Great heroes can be found even here, in the mud and rain.',
  'A little hope, however desperate, is never without worth.',
  'In the end, every plan relies upon a strong arm, and tempered steel.',
  'Fan the flames! Mold the metal! We are raising an army!',
  'Suffer not the lame horse... nor the broken man.	',
  'Can the defiled be consecrated? Can the fallen find rest?',
  'Room by room, hall by hall, we reclaim what is ours.',
  'Wounds to be tended; lessons to be learned.',
  'Regroup. Reassemble. Evil is timeless, after all.',
  'Failure tests the mettle of heart, brain, and body.',
  'You will endure this loss, and learn from it.',
  'You cannot learn a thing you think you know...',
  'We fall so that we may learn to pick ourselves up once again.',
  'Where there is no peril in the task, there can be no glory in its accomplishment.',
  'Great adversity has a beauty - it is the fire that tempers.',
  'The way is lit. The path is clear. We require only the strength to follow it.',
  'The darkness holds much worse than mere trickery and bogeymen.',
  'Glittering gold, trinkets and baubles - paid for in blood.',
  'Finding the stuff is only the first test - now it must be carried home.',
  'Packs laden with loot are often low on supplies.',
  'A spark without kindling is a goal without hope.',
  'A moment of respite. A chance to steel oneself against the coming horrors.',
  'Gnawing hunger sets in, turning the body against itself, weakening the mind…',
  'Packs full of steel and war, but nary a thought given to the plow.',
  'The wounds of war can be healed, but never hidden.',
  'Compassion is a rarity in the fevered pitch of battle.',
  'The blood pumps, the limbs obey!',
  'Death cannot be escaped! But it can be postponed.',
  'Death is patient, it will wait.',
  'Confidence surges as the enemy crumbles!',
  'Press this advantage, give them no quarter!',
  'Continue the onslaught! Destroy. Them. All.',
  'Another abomination cleansed from our lands.',
  'The bigger the beast, the greater the glory.',
  'Great is the weapon that cuts on its own!',
  'Slowly, gently, this is how a life is taken...',
  '	The slow death - unforeseen, unforgiving.',
  'Mortality clarified in a single strike!',
  'Grievous injury, palpable fear...',
  'Death waits for the slightest lapse in concentration.',
  'Ringing ears, blurred vision - the end approaches...',
  'This is no place for the weak, or the foolhardy.',
  'More dust, more ashes, more disappointment',
  'As victories mount, so too will resistance.',
  'Remind yourself that overconfidence is a slow and insidious killer.',
  'Injury and despondence set the stage for heroism... or cowardice.',
  'Even the aged oak will fall to the tempest\'s winds.',
  'One can sometimes find clarity in madness, but only rarely...',
  'There can be no hope in this hell, no hope at all.',
  'Reeling, gasping, taken over the edge into madness!',
  'A moment of valor shines brightest against a backdrop of despair.',
  'Adversity can foster hope, and resilience.',
  'A moment of clarity in the eye of the storm...',
  'Anger is power - unleash it!',
  'Many fall in the face of chaos; but not this one, not today.',
];